minimum_jerk_ros:
  ros__parameters:
    use_sim_time: false
    control_frequency: 25.0
    transform_tolerance: 1.0
    idle_timeout: 10.0
    robot_radius: 0.26
    scaled_obstacle_lookahead_distance: 0.4
    debug_trajectory: true
